repos:
    - hooks:
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: check-case-conflict
          - exclude: \.patch$
            id: trailing-whitespace
          - id: check-merge-conflict
          - id: mixed-line-ending
      repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
    - hooks:
          - id: poetry-check
          - args:
                - --no-update
            id: poetry-lock
      repo: https://github.com/python-poetry/poetry
      rev: 1.4.2
    - hooks:
          - args:
                - --fix
            id: ruff
      repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.0.263
    - hooks:
          - id: black
      repo: https://github.com/psf/black
      rev: 23.3.0
    - hooks:
          - id: markdownlint
      repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.33.0
    - hooks:
          - args:
                - -i
                - --style=Google
            id: clang-format
      repo: https://github.com/pocc/pre-commit-hooks
      rev: v1.3.5