name: Build PCC Firmware

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          python -m pip install pip wheel pipx --upgrade
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install Python Dependencies
        run: poetry install

      - name: Cache PlatformIO
        uses: actions/cache@v3
        with:
          path: .pio
          key: pio-${{ hashFiles('platformio.ini') }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            pio-${{ hashFiles('platformio.ini') }}
            pio

      - name: Setup PlatformIO
        run: poetry run python configure.py

      - name: Run Checks
        run: poetry run pio check --skip-packages

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Firmware
        run: poetry run python build.py --version ${{ env.SHORT_SHA }}

      - name: Upload PCC Firmware Artifact
        if: github.event_name != 'push'
        uses: actions/upload-artifact@v3
        with:
          name: PCC Firmware
          path: .pio/build/adafruit_feather_m4/*.bin

      - name: Create Release
        if: github.event_name != 'pull_request'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.SHORT_SHA }}
          files: .pio/build/adafruit_feather_m4/*.bin
